---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--no-cache --pre'

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  system: bindep.txt
  python: requirements.txt
  python_interpreter:
    package_system: "python312"
    python_path: "/usr/bin/python3.12"

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest

options:
  package_manager_path: /usr/bin/microdnf
  user: root

additional_build_files:
  - src: files/SectigoRSAOrganizationValidationSecureServerCA2.crt
    dest: configs

additional_build_steps:
  prepend_base:
    - COPY _build/configs/SectigoRSAOrganizationValidationSecureServerCA2.crt /usr/share/pki/ca-trust-source/anchors/SectigoRSAOrganizationValidationSecureServerCA2.crt
    - RUN update-ca-trust
    - RUN microdnf install python3.12-devel -y
    - RUN $PKGMGR -y -q install python3-devel
    - RUN git config --global user.name mhallin2
    - RUN git config --global user.email mhallin2@volvocars.com

  append_final:
    - RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 2
    - RUN microdnf install crypto-policies-scripts
    - RUN microdnf -y install iputils
    - RUN update-crypto-policies --set DEFAULT:AD-SUPPORT
    - RUN cp /usr/local/lib/python3.12/site-packages/certifi/cacert.pem /tmp/cacert.pem
    - RUN cat /tmp/cacert.pem /usr/share/pki/ca-trust-source/anchors/SectigoRSAOrganizationValidationSecureServerCA2.crt > /usr/local/lib/python3.12/site-packages/certifi/cacert.pem
